package entities;
// Generated 1 mars 2017 21:51:11 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.*;
/**
 * Voiture generated by hbm2java
 */
@Entity
@Table(name = "voiture", catalog = "test")
@XmlAccessorType(XmlAccessType.NONE)
@XmlRootElement(name="Voiture")
public class Voiture implements java.io.Serializable {

	private Integer numEnrg;
	private int personCin;
	private Date datEnregitre;
	private String depot;
	private String descriptionVoiture;
	private String personName;
	private String personPrenom;
	private String source;

	public Voiture() {
	}

	public Voiture(int personCin, Date datEnregitre, String depot, String descriptionVoiture, String personName,
			String personPrenom, String source) {
		this.personCin = personCin;
		this.datEnregitre = datEnregitre;
		this.depot = depot;
		this.descriptionVoiture = descriptionVoiture;
		this.personName = personName;
		this.personPrenom = personPrenom;
		this.source = source;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@XmlElement(required=true)

	@Column(name = "num_enrg", unique = true, nullable = false)
	public Integer getNumEnrg() {
		return this.numEnrg;
	}

	public void setNumEnrg(Integer numEnrg) {
		this.numEnrg = numEnrg;
	}

	@XmlElement(required=true)
@Column(name = "person_cin", nullable = false)
	public int getPersonCin() {
		return this.personCin;
	}

	public void setPersonCin(int personCin) {
		this.personCin = personCin;
	}

	@XmlElement(required=true)
@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dat_enregitre", nullable = false, length = 19)
	public Date getDatEnregitre() {
		return this.datEnregitre;
	}

	public void setDatEnregitre(Date datEnregitre) {
		this.datEnregitre = datEnregitre;
	}

	@XmlElement(required=true)
@Column(name = "depot", nullable = false)
	public String getDepot() {
		return this.depot;
	}

	public void setDepot(String depot) {
		this.depot = depot;
	}

	@XmlElement(required=true)
@Column(name = "description_voiture", nullable = false)
	public String getDescriptionVoiture() {
		return this.descriptionVoiture;
	}

	public void setDescriptionVoiture(String descriptionVoiture) {
		this.descriptionVoiture = descriptionVoiture;
	}

	@XmlElement(required=true)
@Column(name = "person_name", nullable = false)
	public String getPersonName() {
		return this.personName;
	}

	public void setPersonName(String personName) {
		this.personName = personName;
	}

	@XmlElement(required=true)
@Column(name = "person_prenom", nullable = false)
	public String getPersonPrenom() {
		return this.personPrenom;
	}

	public void setPersonPrenom(String personPrenom) {
		this.personPrenom = personPrenom;
	}

	@XmlElement(required=true)
@Column(name = "source", nullable = false)
	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

}
